### Homework

- Set up the environment
    - You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can the instructions from 06-environment.md.

- Q1. Pandas version
    - What's the version of Pandas that you installed?
        - You can get the version information using the __version__ field: pd.__version__
    - Getting the data:
        - For this homework, we'll use the Laptops Price dataset. Download it from here.
        - You can do it with wget: wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv Or just open it with your browser and click "Save as...".
        - Now read it with Pandas.

- Q2. Records count
    - How many records are in the dataset?

        12
  
        1000
      
        2160
      
        12160
      
- Q3. Laptop brands
    - How many laptop brands are presented in the dataset?

        12
      
        27
      
        28
      
        2160
      
- Q4. Missing values
    - How many columns in the dataset have missing values?

        0
      
        1
      
        2
      
        3
- Q5. Maximum final price
    - What's the maximum final price of Dell notebooks in the dataset?

        869
      
        3691
      
        3849
      
        3936
      
- Q6. Median value of Screen
    - Find the median value of Screen column in the dataset.
    - Next, calculate the most frequent value of the same Screen column.
    - Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
    - Now, calculate the median value of Screen once again.
    - Has it changed?
      Hint: refer to existing mode and median functions to complete the task.

      - Yes
    
      - No
      
- Q7. Sum of weights
    - Select all the "Innjoo" laptops from the dataset.
    - Select only columns RAM, Storage, Screen.
    - Get the underlying NumPy array. Let's call it X.
    - Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
    - Compute the inverse of XTX.
    - Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
    - Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
    - What's the sum of all the elements of the result?
    - Note: You just implemented linear regression. We'll talk about it in the next lesson.

        0.43
      
        45.29
      
        45.58
      
        91.30

- Submit the results
    - Submit your results here: https://courses.datatalks.club/ml-zoomcamp-2024/homework/hw01
    - If your answer doesn't match options exactly, select the closest one

## Q1

In [27]:
import numpy as np
from numpy.linalg import inv
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import urllib.request

#### version of pandas

In [2]:
pd.__version__

'2.2.2'

#### download data

In [ ]:
# using urllib
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv'
filename = 'laptops.csv'
urllib.request.urlretrieve(url, filename)

#### read data

In [3]:
# using pandas

df = pd.read_csv(r"data/laptops.csv")
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

## Q2

#### count rows

In [4]:
df.count()

Laptop          2160
Status          2160
Brand           2160
Model           2160
CPU             2160
RAM             2160
Storage         2160
Storage type    2118
GPU              789
Screen          2156
Touch           2160
Final Price     2160
dtype: int64

## Q3

#### How many laptop brands are presented in the dataset?

In [5]:
print(df['Brand'].nunique())

27


## Q4

#### How many columns in the dataset have missing values?

In [6]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

## Q5

#### What's the maximum final price of Dell notebooks in the dataset?

In [7]:
df.columns

Index(['Laptop', 'Status', 'Brand', 'Model', 'CPU', 'RAM', 'Storage',
       'Storage type', 'GPU', 'Screen', 'Touch', 'Final Price'],
      dtype='object')

In [8]:
df.groupby("Brand")["Final Price"].max()["Dell"]

3936.0

## Q6

#### Find the median value of Screen column in the dataset.

In [9]:
df['Screen'].median()

15.6

#### Find the mode value of Screen column in the dataset.

In [10]:
modeScreenvalue = df['Screen'].mode()[0]
modeScreenvalue

15.6

#### Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

In [11]:
df['Screen'].isnull().sum()

4

In [12]:
df.fillna(modeScreenvalue, inplace=True)
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD      15.6   
1             Go      Intel Celeron    8      256          SSD      15.6   
2     ExpertBook      Intel Core i3    8      256          SSD      15.6   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD      15.6   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD      15.6   
2159        Book  Intel Evo Core i7   16      256          SSD      15.6   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

#### check back on the new null value

In [13]:
df['Screen'].isnull().sum()

0

#### Now, calculate the median value of Screen once again.

In [14]:
df['Screen'].median()

15.6

#### Has it changed? - Hint: refer to existing mode and median functions to complete the task.

- NO

### Q7

####  Select all the "Innjoo" laptops from the dataset.

In [15]:
innjoo_df = df[df["Brand"] == "Innjoo"]
innjoo_df

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type   GPU  Screen Touch  \
1478  Intel Celeron    8      256          SSD  15.6    15.6    No   
1479  Intel Celeron    8      512          SSD  15.6    15.6    No   
1480  Intel Celeron    4       64         eMMC  15.6    14.1    No   
1481  Intel Celeron    6       64         eMMC  15.6    14.1    No   
1482  Intel Celeron    6      128          SSD  15.6    14.1    No   
1483  Intel Celeron    6      128         eMMC  15.6    14.1    No   

      Final Price  
1478       311.37  
1479       392.55  
1480       251.40  
1481       383.61  
1482       317.02  
1483       431.38

#### Select only columns RAM, Storage, Screen. - Get the underlying NumPy array. Let's call it X.

In [56]:
X = innjoo_df[['RAM', 'Storage', 'Screen']].to_numpy()

X = np.array(X)
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

#### Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [58]:
XTX = X@X.T
XTX

array([[ 65843.36, 131379.36,  16635.96,  16651.96,  33035.96,  33035.96],
       [131379.36, 262451.36,  33019.96,  33035.96,  65803.96,  65803.96],
       [ 16635.96,  33019.96,   4310.81,   4318.81,   8414.81,   8414.81],
       [ 16651.96,  33035.96,   4318.81,   4330.81,   8426.81,   8426.81],
       [ 33035.96,  65803.96,   8414.81,   8426.81,  16618.81,  16618.81],
       [ 33035.96,  65803.96,   8414.81,   8426.81,  16618.81,  16618.81]])

#### Compute the inverse of XTX.

In [59]:
# check the det of XTX
det_XTX = np.linalg.det(XTX)
print("Determinant of XTX:", det_XTX)

Determinant of XTX: 0.0


In [60]:
XTX_inv = np.linalg.pinv(XTX)
XTX_inv

array([[ 0.07685672, -0.03540126, -0.12193106,  0.04199099,  0.0139265 ,
         0.0139265 ],
       [-0.03540126,  0.01651252,  0.05568098, -0.01960876, -0.00663032,
        -0.00663032],
       [-0.12193106,  0.05568098,  0.19459549, -0.0659823 , -0.02157929,
        -0.02157929],
       [ 0.04199099, -0.01960876, -0.0659823 ,  0.02329208,  0.00789214,
         0.00789214],
       [ 0.0139265 , -0.00663032, -0.02157929,  0.00789214,  0.00275294,
         0.00275294],
       [ 0.0139265 , -0.00663032, -0.02157929,  0.00789214,  0.00275294,
         0.00275294]])

#### Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

In [61]:
y = [1100, 1300, 800, 900, 1000, 1100]

#### Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [63]:
XT = X.T
a = np.dot(XT, XTX_inv)
a

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [64]:
w = np.dot(a, y)

#### What's the sum of all the elements of the result?

In [65]:
sum_w =  sum(w)
sum_w

91.29988062983693

- By Chisomloius - Chisanloius@gmail.com